services:
  trading-bot:
    build: .
    container_name: trading_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot:/app
    # Optionnel : définir des ressources limites
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: '512M'